### ISSUE TITLE
Error when install

### ISSUE THREAD

**Issue by jorgenlaaker** [frcho/crontask#1]
I got the error:
```
[Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]                                                                                    
  Invalid key "entityManager" found in arguments of method "__construct()" for service "frcho.crontask_default": only integer or $named arguments are allowed.

```
So I changed in the bundle service, frcho.crontask_default, like this:
```
frcho.crontask_default:
        class: Frcho\Bundle\CrontaskBundle\Util\DefaultCommands
        arguments:
            [ "@doctrine.orm.entity_manager", "@service_container" ]
```
Then it worked for me. I'm running Ubuntu 16.4 LAMP
